### ISSUE TITLE
Document use of external databases

### ISSUE THREAD

**Issue by chargio** [ManageIQ/manageiq-schema#37]
using a database.yml configuration file does not change the database configuration, thus preventing the usage of any database that is not local (i.e. any database that is not using sockets but configured as localhost)

**Comment by Fryguy** [comment]
@sergio-ocon Can you clarify your issue?  database.yml works fine, unless I'm misunderstanding.

**Comment by sergio-ocon** [comment]
It is not working for me:

 I have a Vagrant box with a database. I need to connnect to host:localhost to make it work.
https://github.com/sergio-ocon/postgresql-vagrant

The manageiq-schema does not have a databse.yml file. If I copy it to the usual place, it won't recognize the configuration and try to connect using UNIX sockets (and failing as it is not finding the database).

I couldn't do a PR because of this as I could not run tests.

**Comment by Fryguy** [comment]
@carbonin Do you understand what's going on here?  (also wondering if this should move to manageiq proper because it's not a migration specific thing?)

**Comment by carbonin** [comment]
I think the question is about how to set up this repo so that you can run the specs against a database that is not local.

Probably has something to do with running the specs against a dummy rails app. I think the question really is:
"How to I set the database config of the dummy app we run the migration specs against so that I can run the specs if I am not running postgres locally on by development machine?"

Is that right @sergio-ocon ?

**Comment by carbonin** [comment]
If so, I would think that you could set `DATABASE_URL` when running the specs or set your database in `manageiq-schema/spec/dummy/config/database.yml`

**Comment by sergio-ocon** [comment]
That sounds right. I use my vagrant file to avoid littering my laptop (all the funny staff goes into the virtual machine), and for that I need to configure the system to connect to localhost via IP, not UNIX sockets.

**Comment by JPrause** [comment]
@chargio is this still a valid issue? If yes, please remove the stale label. If not can you close.
If there's no update by next week, I'll be closing this issue.

**Comment by chargio** [comment]
Closing this as I don't know
